### ISSUE TITLE
ShellScript coding considered as a comment

### ISSUE THREAD

**Issue by tpfarul** [aaron-bond/better-comments#130] opened 2018-12-12 19:36 UTC
As per below the format "${example##*}" is valid script code, looks it's treated as comments in this plugin.

![image](https://user-images.githubusercontent.com/11402206/49894087-483ebf80-fe0a-11e8-97bd-5c9be6be8aea.png)

**Comment by aaron-bond** [comment] 2019-05-15 10:09
Yeah I've seen this before (similar to #87) but I've not been able to figure out a consistent way to fix it.

The problem is that with the regex detecting comments the only thing that says this is NOT a comment is that it's inside the quotes... maybe that's possible with the regex but I haven't been able to get it working yet. Any help is appreciated if you fancy taking a crack at it.

**Comment by aaron-bond** [comment] 2020-07-14 14:31
Closing as a duplicate, tracking with #87

**Closed by aaron-bond** 2020-07-14 14:31 UTC
Labels: duplicate, help wanted
