### ISSUE TITLE
support multi root workspace

### ISSUE THREAD

**Issue by MarekLew** [aaron-bond/better-comments#27] opened 2018-01-18 10:26 UTC
please support multi root workspace

**Comment by aaron-bond** [comment] 2018-01-18 11:08
Can you please explain what you mean? What's not supported?

**Comment by maezen** [comment] 2018-01-22 22:10
It may happen that Better Comment does not work properly after adding a new folder to a multi-root workspace.
It happened to me. After I closed and reopened the workspace completely, everything worked fine again.
I tried to reproduce the error but without success.

**Comment by aaron-bond** [comment] 2018-01-23 17:32
Ah, I see. I haven't tried that yet. Will test in that scenario soon to be sure.

**Comment by aaron-bond** [comment] 2018-01-23 17:32
Ah, I see. I haven't tried that yet. Will test in that scenario soon to be sure.

**Comment by aaron-bond** [comment] 2018-01-27 14:38
I have been trying to repro this issue without much luck.

#30 seems to say that the same thing is happening (and massive performance impact of multi root workspaces with the plugin).

What I'm trying is: 
    opening a workspace with a single folder
    adding an extra folder with 2 files in it to the workspace
    jumping between those files in the tabs (python and typescript files to test different comment types)

Observed: works as expected and no impact on performance. Any further info is greatly appreciated

**Comment by aaron-bond** [comment] 2018-02-12 20:35
I'm going to have to close this off as I've been unable to reproduce. Will reopen if the problem has repro steps

**Closed by aaron-bond** 2018-02-12 20:35 UTC
