### ISSUE TITLE
Feature Request: Add settings for pre-comment whitespace highlighting 

### ISSUE THREAD

**Issue by SidIcarus** [aaron-bond/better-comments#10] opened 2017-08-14 15:35 UTC
Add a setting to toggle highlighting of pre-comment whitespace.
`better-comments.highlightPreComment: true | false` defaults true

Which is currently how it is handled. 
<img width="279" alt="hightlight" src="https://user-images.githubusercontent.com/3842798/29278871-f5d1681e-80e3-11e7-96b1-958d2bb482ae.png">

**Comment by aaron-bond** [comment] 2017-08-21 15:52
Closing as this is a duplicate of #7

**Closed by aaron-bond** 2017-08-21 15:52 UTC
